### ISSUE TITLE
Chat IDs changed after creating a new group chat.

### ISSUE THREAD

**Issue by TemeV** [Kaffeine/telegram-qt#10]
It seems Chat IDs can change when adding (and maybe removing also) groups. I added a new group and it came up with id 4 and the old "chat4" became "chat5".

**Comment by Kaffeine** [comment]
I can not reproduce the issue and don't see how it can happen.
(I reorganized some public chat id things. It's not actually related, but id should be bit more robust now.)

**Comment by Kaffeine** [comment]
Chat ID is now actual Telegram group chat id, so:
1) Chat IDs are changed after commit 4a5748642cf5bfbc91512a0e6dc952222cad4b1a
2) Chat IDs would never ever be changed anymore. If only they would introduce dynamic chat ids on the server side... :)
