### ISSUE TITLE
Can't cmake on Debian Stretch

### ISSUE THREAD

**Issue by criztovyl** [Kaffeine/telegram-qt#12]
Hello,

I'm unable to build telegram-qt on Debian Stretch/Testing, it alway fails with following error when I use `cmake telegram-qt` (within repo)

    CMake Error at CMakeLists.txt:68 (QT5_WRAP_CPP):
      Unknown CMake command "QT5_WRAP_CPP".

    CMake Warning (dev) in CMakeLists.txt:
      No cmake_minimum_required command is present.  A line of code such as

        cmake_minimum_required(VERSION 3.3)

      should be added at the top of the file.  The version specified may be lower
      if you wish to support older CMake versions for this project.  For more
      information run "cmake --help-policy CMP0000".
    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Configuring incomplete, errors occurred!

Have installed qt5.
`cmake .` in repo throws

    CMake Error at /usr/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
      Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
      system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
      OPENSSL_INCLUDE_DIR)
    Call Stack (most recent call first):
      /usr/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
      /usr/share/cmake-3.3/Modules/FindOpenSSL.cmake:334 (find_package_handle_standard_args)
      CMakeLists.txt:37 (find_package)

    -- Configuring incomplete, errors occurred!

I have openssl installed.
Thx

**Comment by criztovyl** [comment]
Found my mistake: hadn't installed libssl-dev.
And shouldn't use `cmake telegram-qt`, only use `cmake .`
Am I right so far?

**Comment by Kaffeine** [comment]
Common practice is to perform "out-of-source" build.

    git clone https://github.com/Kaffeine/telegram-qt.git
    mkdir telegram-qt-build
    cd telegram-qt-build
    cmake ../telegram-qt

You're right, cmake should be run only on top-level directory (`cmake .` in your case).

**Comment by criztovyl** [comment]
Hm, when I do it your way, the created `telegram-qt-build` stays empty, I can only make in cloned directory, is that correct?
Furthermore, when I compile it there, I can't "use" it with `telepathy-morse`, it does not find the `.cmake` file. It is present in `telegram-qt/telegram-qt` and in `/usr/local/lib/cmake/TelegramQt5/TelegramQt5Config.cmake`? (Is it a cmake problem?)

**Comment by Kaffeine** [comment]
>the created telegram-qt-build stays empty, I can only make in cloned directory, is that correct?

No, this is not correct.
CMake creates files in current directory, so you'll have CMakeCache.txt and other files here:

```
kaffeine@gid0pc ~/devel/tmp $ git clone https://github.com/Kaffeine/telegram-qt.git
Cloning into 'telegram-qt'...
remote: Counting objects: 3022, done.
remote: Total 3022 (delta 0), reused 0 (delta 0), pack-reused 3022
Receiving objects: 100% (3022/3022), 881.04 KiB | 354.00 KiB/s, done.
Resolving deltas: 100% (2298/2298), done.
Checking connectivity... done.
kaffeine@gid0pc ~/devel/tmp $ mkdir telegram-qt-build
kaffeine@gid0pc ~/devel/tmp $ cd telegram-qt-build
kaffeine@gid0pc ~/devel/tmp/telegram-qt-build $ cmake ../telegram-qt
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1k") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kaffeine/devel/tmp/telegram-qt-build
kaffeine@gid0pc ~/devel/tmp/telegram-qt-build $ ls
CMakeCache.txt  CMakeFiles  Makefile  cmake_install.cmake  telegram-qt
kaffeine@gid0pc ~/devel/tmp/telegram-qt-build $
```

>Furthermore, when I compile it there, I can't "use" it with telepathy-morse, it does not find the .cmake file. It is present in telegram-qt/telegram-qt and in /usr/local/lib/cmake/TelegramQt5/TelegramQt5Config.cmake? (Is it a cmake problem?)

It looks like a problem with CMake configuration. Try to do `export CMAKE_PREFIX_PATH=/usr/local/lib/cmake` before run CMake for Morse.

**Comment by criztovyl** [comment]
Ah, my `telegram-qt` dir wasn't clean, to be on the safe side I deleted and (re-)cloned it. Now it works as intended.

But Morse still fails. `cmake` still does not find the `...config.cmake` file. But that's more an Morse/CMake issue, isn't it? (I set the prefix path as you recommended)

    Warning: If TelepathyQt version < 0.9.7, then group chat support will be disabled.
    CMake Error at CMakeLists.txt:15 (find_package):
      By not providing "FindTelepathyQt5.cmake" in CMAKE_MODULE_PATH this project
      has asked CMake to find a package configuration file provided by
      "TelepathyQt5", but CMake did not find one.

      Could not find a package configuration file provided by "TelepathyQt5"
      (requested version 0.9.6) with any of the following names:

        TelepathyQt5Config.cmake
        telepathyqt5-config.cmake

      Add the installation prefix of "TelepathyQt5" to CMAKE_PREFIX_PATH or set
      "TelepathyQt5_DIR" to a directory containing one of the above files.  If
      "TelepathyQt5" provides a separate development package or SDK, be sure it
      has been installed.


    -- Configuring incomplete, errors occurred!

**Comment by Kaffeine** [comment]
There is no any issue with code, but only with your setup and configuration.
As it's said, you need recent TelepathyQt. Install devel TelepathyQt5 package (with Service library) and configuration step would be passed successfully.

**Comment by criztovyl** [comment]
\*facepalm\* Didn't get that its TelepathyQt5 and not TelegramQt5...
Trying again now.

**Comment by criztovyl** [comment]
Works.
