### ISSUE TITLE
Disconnecting not always detected

### ISSUE THREAD

**Issue by TemeV** [Kaffeine/telegram-qt#13]
CTelegramDispatcher::whenConnectionStatusChanged doesn't seem to do anything when disconnecting happens and reason is not ConnectionStatusReasonTimeout.
I had this in my log:
>void CTelegramDispatcher::whenConnectionStatusChanged(int, int, quint32) status 0 reason 0 dc 2

After that Morse was still "online" but did not receive any messages. Switching Morse to offline and back online got the messages flowing again.

**Comment by Kaffeine** [comment]
Indeed. I'm going to fix this. Thanks!

**Comment by Kaffeine** [comment]
I think I fixed the issue via commit 78ca5c6cc3ddde1944084adae8e6ef87d512113f.

**Comment by TemeV** [comment]
I think that should fix it, but I don't really know how to reproduce the issue though.
