### ISSUE TITLE
getting error 401 AUTH_KEY_UNREGISTERED when using secret file

### ISSUE THREAD

**Issue by caio2k** [Kaffeine/telegram-qt#16]
Hi there,

I've been using the testApp to develop my client and maybe I'm missing something. When I register following the USAGE file I manage to connect and see the messages. Then I save the secretfile and log out. However when I use the secretfile to connect again, I get 401 AUTH_KEY_UNREGISTERED errors. I'm not sure it is related with a bad understanding or due to QT4.7 incompatibility. Did you see this behavior already?

Thanks for your time!

**Comment by Kaffeine** [comment]
>Then I save the secretfile and log out.

"Log out" is https://core.telegram.org/method/auth.logOut . It terminates session and "unregister" the auth key.

If you want to set own status to offline, then use CTelegramCore::setOnlineStatus() method instead. The method calls https://core.telegram.org/method/account.updateStatus .

**Comment by Kaffeine** [comment]
Currently there is an issue with authorization process, which I'm going to fix soon. If you can "see the messages" after authentication, then the issue doesn't affect you.

**Comment by Kaffeine** [comment]
I landed a lot of authentication-related fixes and this issue probably fixed months ago.
Feel free to reopen if you still have the issue on recent TelegramQt.
