### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by lindhe** [Kaffeine/telegram-qt#25]
Sorry if you think I have not made enough research and shouldn't ask this question, but here goes.

I use telegram on Linux. I don't know much about qt. Do I benefit from installing your thing?

Saw it on the Arch Linux `community/telegram-qt`, so I though it must be something pretty dope. But I don't understand what it does. Your README is probably fine for anyone that already knows what this does, but for a layman like me that's just browsing for cool programs, it's not very informative.

**Comment by Kaffeine** [comment]
Hi Andreas,

this is a library for [Morse](https://github.com/TelepathyIM/telepathy-morse) - Telegram connection manager for Telepathy communication framework.
There are Telepathy clients for KDE, Gnome, UbuntuPhone, SailfishOS and more DE. More info about Morse available here: https://akulichalexandr.wordpress.com/2016/09/16/telegram-connection-manager-morse-released/

Telegram has a number of features, not supported by Telepathy specification, so if you actually use Telegram for something more, than 1-to-1 plain text communication, then this project won't work for you well (yet).
