### ISSUE TITLE
Telegram-qt vs Telegram

### ISSUE THREAD

**Issue by Quill88** [Kaffeine/telegram-qt#26]
Hi,
Is it possible to send messages to other Telegram client apps using your library?
I could send and receive messages only between 2 Telegram-qt testapp, but those messages aren't displayed at mobile and win apps.
BR,
Aleks

**Comment by Kaffeine** [comment]
Hi, Aleks.
The library implements Telegram protocol and it is aimed to communicate with any Telegram client. Last time it worked well; I can not test it right now, but it should work. The most important thing which is missing yet, is Channel / Mega group support. I did some initial support, but not pushed it yet. I think I'll finish it the next week. After that I'll test again everything and release 0.2.0 version.

**Comment by Kaffeine** [comment]
I hammered a number of various bugs and I believe this issue is solved.
Feel free to reopen this issue if there is a problem with personal messaging.
