### ISSUE TITLE
Making telegram-qt compaible with qt-pods

### ISSUE THREAD

**Issue by cybercatalyst** [Kaffeine/telegram-qt#4]
See here to get an idea of qt-pods:
https://github.com/cybercatalyst/qt-pods

If you need assistance, don't hesitate to ask. My time is limited since I am helping on-boarding a couple of other projects, too, but I am glad if I can help.

**Comment by Kaffeine** [comment]
I like the basic idea of qt-pods, but I don't think that the telegram API worth it. I like qtjack project, as there is a reason to have many jack clients. Number of other fragments are widely useful as well.
At same time, I don't see any reasons to have many telegram clients. I think there will be just a few clients: 1) telepathy-based client (for KDE, Gnome, Sailfish, etc), 2) client for Blackberry 3) may be one another client for desktops.
Only the last one client does not exists yet, so may be will have some benefit from telegram-pod usage. IMO, worthless.
After all, I found requirements too strict and inconvenient.
("The repository root contains a *.pro file that is a static lib template.
The *.pro must have exactly have the same name as the repository.")
Many distributions (e.g. Debian) require library to be shared one.
Once qt-pods will be bit more flexible, so it'll be possible to create some "pod.description" file with the fragment specification, I'll do it. Actually, telegram-qt almost meet the requirements, but have "static lib pro file" in the "telegram-qt" subdirectory.
