### ISSUE TITLE
Question for BlackBerry 10

### ISSUE THREAD

**Issue by doctorrokter** [Kaffeine/telegram-qt#45]
Hi Alexander!

I'm a BlackBerry 10 dev (as a hobby) and looking for some useful libs which could help me to build Telegram client for BB 10. Is it possible with your lib? I mean I want to implement fully-featured (or almost) client, or at least messaging with all features: text, smiles, stickers etc.

Also, if so, BB 10 supports only Qt 4.8, not greater. Is it will be very big effort to compile your lib for qt 4.8 with some patches? I need only stable **backend**, all native UI and BB 10 look and feel I can implement without any problems.

Thanks!

**Comment by Kaffeine** [comment]
Hello.
I removed Qt4 support by commit df12de3f5afa3eaec1332f8180509fa325cd1709, but it should be not that hard to restore the compatibility. Do you have a C++11 compiler?
I'll try to get 4.8 somewhere and compile the project.

**Comment by Kaffeine** [comment]
I made a branch for you: https://github.com/Kaffeine/telegram-qt/tree/qt4

I only fixed compilation so far; I'll test the library tomorrow.

**Comment by doctorrokter** [comment]
Thanks for your quick reply!

For BB10 development used QCC compiler (for QNX operation system). It bundled with qt4 in BB Native SDK. Rather I compile through IDE than directly from command line :) 

Will try to include your lib into the project.

**Comment by mrPjer** [comment]
Back when Telegram held their BlackBerry 10 development contest, we started work on a Telegram client for BlackBerry 10, but development eventually stopped due to a lack of time on all of the developers. It's far from fully functional, but if you want to take a look at the code, it's available here: https://github.com/mrPjer/tgBB10

**Comment by doctorrokter** [comment]
Thanks for your comment here, it's very helpful. Main problems are that BB 10 does not support qt5 and greater, and also qcc compiler for BB 10  does not support c++11. These problems very annoying. Tried to compile this lib and was kicked by compiler, because of lib contains c++11 features and I need to "transpile" to older standard manually before compiling. But anyway, thanks guys for helping!
