### ISSUE TITLE
Make a SIP for PyQt lovers

### ISSUE THREAD

**Issue by SafaAlfulaij** [Kaffeine/telegram-qt#5]
Thanks for this great library!
Could you please make a SIP package for PyQt5 to be used in Python apps? :-)

**Comment by Kaffeine** [comment]
Hello. I know nothing about Python/SIP and have little-to-no time for my projects, but will see, what I can do.
I have to say that the API is not stable yet. Media messages processing will be changed.

**Comment by SafaAlfulaij** [comment]
Since I stopped using Telegram, I'm not interested in this anymore. Thanks a lot for your work.

**Comment by kskarthik** [comment]
is this a qt user interface for telegram ?
