### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by Ramizak** [Kaffeine/telegram-qt#8]
hey guys,

Just a bit newbie in these kind of issues.. Would you please help me with compiling ?
I need Cmake, Open SS, MySQl ( not sure) also I have full installation of Visual Studio 2012 /
but when I just use cmake to generate project file , I get errors like this : 
Would you please give a good and step by step guide to compile it?

The C compiler identification is unknown
The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:1 (project):
 No CMAKE_CXX_COMPILER could be found.

Configuring incomplete, errors occurred!
See also "D:/bot/testg/CMakeFiles/CMakeOutput.log".
See also "D:/bot/testg/CMakeFiles/CMakeError.log".

**Comment by Kaffeine** [comment]
Hello.
I'm sorry, I have no idea, how to setup CMake and the project dependencies on Windows.
You can try to build the project using https://github.com/Walkman100/telegram-qt
If I understand correctly, you don't need CMake, but you can build in Visual Studio itself.

**Comment by Ramizak** [comment]
getting compatibility error, did you use any special sdk for it?

**Comment by Kaffeine** [comment]
1) Outdated
2) I have no idea about Windows. Probably the library will work, but I can not help you with build instructions.
