### ISSUE TITLE
Thanks for future

### ISSUE THREAD

**Issue by fcore117** [Kaffeine/telegram-qt#83]
It is good to see someone is developing C++ Telegram server alternative as this can insure future alternative Telegram server if something serious happens with official servers. Please close this if you(developer) see this.

**Comment by Kaffeine** [comment]
It might be interesting for you that I also prototyped a support for Server-to-Server XMPP protocol.
The protocols aren't that compatible and it would be easier to support Matrix S2S but I could not find a library for that.

[xmpp-telegram-vol2.webm](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/NeSUlZqrCrnnrtdtQUnccKAO) - A Telegram and XMPP users talking to each other via federated servers (TelegramQt and QXmpp servers in this video).
[xmpp-telegram-vol3.webm](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/wCUoUnxgwzLVvNwtNwXQAbHc) - Telegram server hosts a room for Prosody XMPP server via S2S connection.

**Comment by fcore117** [comment]
As for now i am very happy Telegram user as it is only one of few fast chat apps thanks to C++, whole world are gone mad and most uses heavy bloat with Electron and node.js horrors.

Thanks for keeping interest on alternative ways for Telegram. We never know what might happen to official Telegram.
