### ISSUE TITLE
Wrong qt5 lib dir

### ISSUE THREAD

**Issue by neochapay** [Kaffeine/telegram-qt#88]
I build with
```cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_WITH_QT_VERSION=Qt5 -DBUILD_CLIENT=TRUE```
But on make install i got

```-- Installing: /usr/lib/qt6/qml/TelegramQt/libTelegramQmlPlugin.so
-- Installing: /usr/lib/qt6/qml/TelegramQt/qmldir
-- Installing: /usr/lib/qt6/qml/TelegramQt/plugins.qmltypes
```
And when try run example client i got

```QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:6:1: module "TelegramQt" is not installed
Unable to instantiate the root component.
Ensure that the application is installed correctly and double check that QML2_IMPORT_PATH environment variable is set to the correct installation directory with TelegramQt inside.
If you built the project from CMake then ensure that you did
    cmake --build <your_build_directory> --target install
and also follow the hint about QML2_IMPORT_PATH from CMake configure output.
````

**Comment by Kaffeine** [comment]
There is `INSTALL_QML_IMPORT_DIR` cached variable.
Probably you have Qt6 and initially you've configured the project with default options (which prefers Qt6). It sets the cached var to `/usr/lib/qt6/qml`.

Try to clear the build directory and configure the project again.
I know it is pity to have this var `CACHE` but there was a hard reason for that (I don't remember the reason those years later).
