### ISSUE TITLE
Telegram-Qt got stuck while connecting.

### ISSUE THREAD

**Issue by TemeV** [Kaffeine/telegram-qt#9]
Telegram-qt (or telepathy-morse) got stuck while travelling through an area with bad reception. Here is the log https://gist.github.com/TemeV/0a342c80d1d45a376b1f

Maybe some timeout to connection phase could be added to make sure that the connection is either established or changed to disconnected state, not stuck somewhere in between.

**Comment by TemeV** [comment]
Sorry about noise in changing the title and opening and closing this. I managed to make a couple of miss clicks while thinking if I'll file this issue now or investigate more first.

**Comment by Kaffeine** [comment]
With cf6c20eb6f4eb35e8d68b2618d133e52515cd5c3 we have timeout control since socket connection, so "no stuck anymore".
